### ISSUE TITLE
Install the project

### ISSUE THREAD

**Issue by 97shivank** [97shivank/Hotel-Site-with-Django#4]
Install the django project in local Pc and Open a pull request adding screenshots of successfully installed project in screenshot folder.

**Comment by VineetS086** [comment]
Did it...
![Screenshot 2020-12-06 084426](https://user-images.githubusercontent.com/68197705/101270478-73610d00-379f-11eb-919e-ac2678ee18e7.png)

**Comment by 97shivank** [comment]
@VineetS086  kindly review the issue again. thanks

**Comment by AyushRajSharma** [comment]
@97shivank I have to install and run on my local machine and upload ss in screenshot folder ?
